[build]
  publish = "dist"
  command = "NODE_ENV=production npm run build && cd functions && npm install"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
