[build]
command = "npm install && vite build"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"

